# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'PracticalEnglish' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase', '>= 2.5.1'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Invites'
	pod 'MBProgressHUD', '~> 1.0'
	pod 'PDFReader', '~> 2.1'
	pod 'RealmSwift'
  # Pods for PracticalEnglish

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
    end
  end
end